/**
 * Alertmanager API
 * API of the Prometheus Alertmanager (https://github.com/prometheus/alertmanager)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AlertmanagerConfig from './AlertmanagerConfig';
import ClusterStatus from './ClusterStatus';
import VersionInfo from './VersionInfo';

/**
 * The AlertmanagerStatus model module.
 * @module model/AlertmanagerStatus
 * @version 0.0.1
 */
class AlertmanagerStatus {
    /**
     * Constructs a new <code>AlertmanagerStatus</code>.
     * @alias module:model/AlertmanagerStatus
     * @param cluster {module:model/ClusterStatus} 
     * @param versionInfo {module:model/VersionInfo} 
     * @param config {module:model/AlertmanagerConfig} 
     * @param uptime {Date} 
     */
    constructor(cluster, versionInfo, config, uptime) { 
        
        AlertmanagerStatus.initialize(this, cluster, versionInfo, config, uptime);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, cluster, versionInfo, config, uptime) { 
        obj['cluster'] = cluster;
        obj['versionInfo'] = versionInfo;
        obj['config'] = config;
        obj['uptime'] = uptime;
    }

    /**
     * Constructs a <code>AlertmanagerStatus</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AlertmanagerStatus} obj Optional instance to populate.
     * @return {module:model/AlertmanagerStatus} The populated <code>AlertmanagerStatus</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AlertmanagerStatus();

            if (data.hasOwnProperty('cluster')) {
                obj['cluster'] = ClusterStatus.constructFromObject(data['cluster']);
            }
            if (data.hasOwnProperty('versionInfo')) {
                obj['versionInfo'] = VersionInfo.constructFromObject(data['versionInfo']);
            }
            if (data.hasOwnProperty('config')) {
                obj['config'] = AlertmanagerConfig.constructFromObject(data['config']);
            }
            if (data.hasOwnProperty('uptime')) {
                obj['uptime'] = ApiClient.convertToType(data['uptime'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/ClusterStatus} cluster
 */
AlertmanagerStatus.prototype['cluster'] = undefined;

/**
 * @member {module:model/VersionInfo} versionInfo
 */
AlertmanagerStatus.prototype['versionInfo'] = undefined;

/**
 * @member {module:model/AlertmanagerConfig} config
 */
AlertmanagerStatus.prototype['config'] = undefined;

/**
 * @member {Date} uptime
 */
AlertmanagerStatus.prototype['uptime'] = undefined;






export default AlertmanagerStatus;

