/**
 * Alertmanager API
 * API of the Prometheus Alertmanager (https://github.com/prometheus/alertmanager)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GettableAlert from './GettableAlert';
import Receiver from './Receiver';

/**
 * The AlertGroup model module.
 * @module model/AlertGroup
 * @version 0.0.1
 */
class AlertGroup {
    /**
     * Constructs a new <code>AlertGroup</code>.
     * @alias module:model/AlertGroup
     * @param labels {Object.<String, String>} 
     * @param receiver {module:model/Receiver} 
     * @param alerts {Array.<module:model/GettableAlert>} 
     */
    constructor(labels, receiver, alerts) { 
        
        AlertGroup.initialize(this, labels, receiver, alerts);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, labels, receiver, alerts) { 
        obj['labels'] = labels;
        obj['receiver'] = receiver;
        obj['alerts'] = alerts;
    }

    /**
     * Constructs a <code>AlertGroup</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AlertGroup} obj Optional instance to populate.
     * @return {module:model/AlertGroup} The populated <code>AlertGroup</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AlertGroup();

            if (data.hasOwnProperty('labels')) {
                obj['labels'] = ApiClient.convertToType(data['labels'], {'String': 'String'});
            }
            if (data.hasOwnProperty('receiver')) {
                obj['receiver'] = Receiver.constructFromObject(data['receiver']);
            }
            if (data.hasOwnProperty('alerts')) {
                obj['alerts'] = ApiClient.convertToType(data['alerts'], [GettableAlert]);
            }
        }
        return obj;
    }


}

/**
 * @member {Object.<String, String>} labels
 */
AlertGroup.prototype['labels'] = undefined;

/**
 * @member {module:model/Receiver} receiver
 */
AlertGroup.prototype['receiver'] = undefined;

/**
 * @member {Array.<module:model/GettableAlert>} alerts
 */
AlertGroup.prototype['alerts'] = undefined;






export default AlertGroup;

