/**
 * Alertmanager API
 * API of the Prometheus Alertmanager (https://github.com/prometheus/alertmanager)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AlertStatus model module.
 * @module model/AlertStatus
 * @version 0.0.1
 */
class AlertStatus {
    /**
     * Constructs a new <code>AlertStatus</code>.
     * @alias module:model/AlertStatus
     * @param state {module:model/AlertStatus.StateEnum} 
     * @param silencedBy {Array.<String>} 
     * @param inhibitedBy {Array.<String>} 
     */
    constructor(state, silencedBy, inhibitedBy) { 
        
        AlertStatus.initialize(this, state, silencedBy, inhibitedBy);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, state, silencedBy, inhibitedBy) { 
        obj['state'] = state;
        obj['silencedBy'] = silencedBy;
        obj['inhibitedBy'] = inhibitedBy;
    }

    /**
     * Constructs a <code>AlertStatus</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AlertStatus} obj Optional instance to populate.
     * @return {module:model/AlertStatus} The populated <code>AlertStatus</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AlertStatus();

            if (data.hasOwnProperty('state')) {
                obj['state'] = ApiClient.convertToType(data['state'], 'String');
            }
            if (data.hasOwnProperty('silencedBy')) {
                obj['silencedBy'] = ApiClient.convertToType(data['silencedBy'], ['String']);
            }
            if (data.hasOwnProperty('inhibitedBy')) {
                obj['inhibitedBy'] = ApiClient.convertToType(data['inhibitedBy'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/AlertStatus.StateEnum} state
 */
AlertStatus.prototype['state'] = undefined;

/**
 * @member {Array.<String>} silencedBy
 */
AlertStatus.prototype['silencedBy'] = undefined;

/**
 * @member {Array.<String>} inhibitedBy
 */
AlertStatus.prototype['inhibitedBy'] = undefined;





/**
 * Allowed values for the <code>state</code> property.
 * @enum {String}
 * @readonly
 */
AlertStatus['StateEnum'] = {

    /**
     * value: "unprocessed"
     * @const
     */
    "unprocessed": "unprocessed",

    /**
     * value: "active"
     * @const
     */
    "active": "active",

    /**
     * value: "suppressed"
     * @const
     */
    "suppressed": "suppressed"
};



export default AlertStatus;

