/**
 * Alertmanager API
 * API of the Prometheus Alertmanager (https://github.com/prometheus/alertmanager)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Alert model module.
 * @module model/Alert
 * @version 0.0.1
 */
class Alert {
    /**
     * Constructs a new <code>Alert</code>.
     * @alias module:model/Alert
     * @param labels {Object.<String, String>} 
     */
    constructor(labels) { 
        
        Alert.initialize(this, labels);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, labels) { 
        obj['labels'] = labels;
    }

    /**
     * Constructs a <code>Alert</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Alert} obj Optional instance to populate.
     * @return {module:model/Alert} The populated <code>Alert</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Alert();

            if (data.hasOwnProperty('labels')) {
                obj['labels'] = ApiClient.convertToType(data['labels'], {'String': 'String'});
            }
            if (data.hasOwnProperty('generatorURL')) {
                obj['generatorURL'] = ApiClient.convertToType(data['generatorURL'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Object.<String, String>} labels
 */
Alert.prototype['labels'] = undefined;

/**
 * @member {String} generatorURL
 */
Alert.prototype['generatorURL'] = undefined;






export default Alert;

