/**
 * Alertmanager API
 * API of the Prometheus Alertmanager (https://github.com/prometheus/alertmanager)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PeerStatus from './PeerStatus';

/**
 * The ClusterStatus model module.
 * @module model/ClusterStatus
 * @version 0.0.1
 */
class ClusterStatus {
    /**
     * Constructs a new <code>ClusterStatus</code>.
     * @alias module:model/ClusterStatus
     * @param status {module:model/ClusterStatus.StatusEnum} 
     */
    constructor(status) { 
        
        ClusterStatus.initialize(this, status);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, status) { 
        obj['status'] = status;
    }

    /**
     * Constructs a <code>ClusterStatus</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ClusterStatus} obj Optional instance to populate.
     * @return {module:model/ClusterStatus} The populated <code>ClusterStatus</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ClusterStatus();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('peers')) {
                obj['peers'] = ApiClient.convertToType(data['peers'], [PeerStatus]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
ClusterStatus.prototype['name'] = undefined;

/**
 * @member {module:model/ClusterStatus.StatusEnum} status
 */
ClusterStatus.prototype['status'] = undefined;

/**
 * @member {Array.<module:model/PeerStatus>} peers
 */
ClusterStatus.prototype['peers'] = undefined;





/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
ClusterStatus['StatusEnum'] = {

    /**
     * value: "ready"
     * @const
     */
    "ready": "ready",

    /**
     * value: "settling"
     * @const
     */
    "settling": "settling",

    /**
     * value: "disabled"
     * @const
     */
    "disabled": "disabled"
};



export default ClusterStatus;

