/**
 * Alertmanager API
 * API of the Prometheus Alertmanager (https://github.com/prometheus/alertmanager)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SilenceStatus from './SilenceStatus';

/**
 * The GettableSilenceAllOf model module.
 * @module model/GettableSilenceAllOf
 * @version 0.0.1
 */
class GettableSilenceAllOf {
    /**
     * Constructs a new <code>GettableSilenceAllOf</code>.
     * @alias module:model/GettableSilenceAllOf
     * @param id {String} 
     * @param status {module:model/SilenceStatus} 
     * @param updatedAt {Date} 
     */
    constructor(id, status, updatedAt) { 
        
        GettableSilenceAllOf.initialize(this, id, status, updatedAt);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, status, updatedAt) { 
        obj['id'] = id;
        obj['status'] = status;
        obj['updatedAt'] = updatedAt;
    }

    /**
     * Constructs a <code>GettableSilenceAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GettableSilenceAllOf} obj Optional instance to populate.
     * @return {module:model/GettableSilenceAllOf} The populated <code>GettableSilenceAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GettableSilenceAllOf();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = SilenceStatus.constructFromObject(data['status']);
            }
            if (data.hasOwnProperty('updatedAt')) {
                obj['updatedAt'] = ApiClient.convertToType(data['updatedAt'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
GettableSilenceAllOf.prototype['id'] = undefined;

/**
 * @member {module:model/SilenceStatus} status
 */
GettableSilenceAllOf.prototype['status'] = undefined;

/**
 * @member {Date} updatedAt
 */
GettableSilenceAllOf.prototype['updatedAt'] = undefined;






export default GettableSilenceAllOf;

