/**
 * Alertmanager API
 * API of the Prometheus Alertmanager (https://github.com/prometheus/alertmanager)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GettableSilenceAllOf from './GettableSilenceAllOf';
import Matcher from './Matcher';
import Silence from './Silence';
import SilenceStatus from './SilenceStatus';

/**
 * The GettableSilence model module.
 * @module model/GettableSilence
 * @version 0.0.1
 */
class GettableSilence {
    /**
     * Constructs a new <code>GettableSilence</code>.
     * @alias module:model/GettableSilence
     * @implements module:model/GettableSilenceAllOf
     * @implements module:model/Silence
     * @param id {String} 
     * @param status {module:model/SilenceStatus} 
     * @param updatedAt {Date} 
     * @param matchers {Array.<module:model/Matcher>} 
     * @param startsAt {Date} 
     * @param endsAt {Date} 
     * @param createdBy {String} 
     * @param comment {String} 
     */
    constructor(id, status, updatedAt, matchers, startsAt, endsAt, createdBy, comment) { 
        GettableSilenceAllOf.initialize(this, id, status, updatedAt);Silence.initialize(this, matchers, startsAt, endsAt, createdBy, comment);
        GettableSilence.initialize(this, id, status, updatedAt, matchers, startsAt, endsAt, createdBy, comment);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, status, updatedAt, matchers, startsAt, endsAt, createdBy, comment) { 
        obj['id'] = id;
        obj['status'] = status;
        obj['updatedAt'] = updatedAt;
        obj['matchers'] = matchers;
        obj['startsAt'] = startsAt;
        obj['endsAt'] = endsAt;
        obj['createdBy'] = createdBy;
        obj['comment'] = comment;
    }

    /**
     * Constructs a <code>GettableSilence</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GettableSilence} obj Optional instance to populate.
     * @return {module:model/GettableSilence} The populated <code>GettableSilence</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GettableSilence();
            GettableSilenceAllOf.constructFromObject(data, obj);
            Silence.constructFromObject(data, obj);

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = SilenceStatus.constructFromObject(data['status']);
            }
            if (data.hasOwnProperty('updatedAt')) {
                obj['updatedAt'] = ApiClient.convertToType(data['updatedAt'], 'Date');
            }
            if (data.hasOwnProperty('matchers')) {
                obj['matchers'] = ApiClient.convertToType(data['matchers'], [Matcher]);
            }
            if (data.hasOwnProperty('startsAt')) {
                obj['startsAt'] = ApiClient.convertToType(data['startsAt'], 'Date');
            }
            if (data.hasOwnProperty('endsAt')) {
                obj['endsAt'] = ApiClient.convertToType(data['endsAt'], 'Date');
            }
            if (data.hasOwnProperty('createdBy')) {
                obj['createdBy'] = ApiClient.convertToType(data['createdBy'], 'String');
            }
            if (data.hasOwnProperty('comment')) {
                obj['comment'] = ApiClient.convertToType(data['comment'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
GettableSilence.prototype['id'] = undefined;

/**
 * @member {module:model/SilenceStatus} status
 */
GettableSilence.prototype['status'] = undefined;

/**
 * @member {Date} updatedAt
 */
GettableSilence.prototype['updatedAt'] = undefined;

/**
 * @member {Array.<module:model/Matcher>} matchers
 */
GettableSilence.prototype['matchers'] = undefined;

/**
 * @member {Date} startsAt
 */
GettableSilence.prototype['startsAt'] = undefined;

/**
 * @member {Date} endsAt
 */
GettableSilence.prototype['endsAt'] = undefined;

/**
 * @member {String} createdBy
 */
GettableSilence.prototype['createdBy'] = undefined;

/**
 * @member {String} comment
 */
GettableSilence.prototype['comment'] = undefined;


// Implement GettableSilenceAllOf interface:
/**
 * @member {String} id
 */
GettableSilenceAllOf.prototype['id'] = undefined;
/**
 * @member {module:model/SilenceStatus} status
 */
GettableSilenceAllOf.prototype['status'] = undefined;
/**
 * @member {Date} updatedAt
 */
GettableSilenceAllOf.prototype['updatedAt'] = undefined;
// Implement Silence interface:
/**
 * @member {Array.<module:model/Matcher>} matchers
 */
Silence.prototype['matchers'] = undefined;
/**
 * @member {Date} startsAt
 */
Silence.prototype['startsAt'] = undefined;
/**
 * @member {Date} endsAt
 */
Silence.prototype['endsAt'] = undefined;
/**
 * @member {String} createdBy
 */
Silence.prototype['createdBy'] = undefined;
/**
 * @member {String} comment
 */
Silence.prototype['comment'] = undefined;




export default GettableSilence;

