/**
 * Alertmanager API
 * API of the Prometheus Alertmanager (https://github.com/prometheus/alertmanager)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Matcher model module.
 * @module model/Matcher
 * @version 0.0.1
 */
class Matcher {
    /**
     * Constructs a new <code>Matcher</code>.
     * @alias module:model/Matcher
     * @param name {String} 
     * @param value {String} 
     * @param isRegex {Boolean} 
     */
    constructor(name, value, isRegex) { 
        
        Matcher.initialize(this, name, value, isRegex);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, value, isRegex) { 
        obj['name'] = name;
        obj['value'] = value;
        obj['isRegex'] = isRegex;
    }

    /**
     * Constructs a <code>Matcher</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Matcher} obj Optional instance to populate.
     * @return {module:model/Matcher} The populated <code>Matcher</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Matcher();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'String');
            }
            if (data.hasOwnProperty('isRegex')) {
                obj['isRegex'] = ApiClient.convertToType(data['isRegex'], 'Boolean');
            }
            if (data.hasOwnProperty('isEqual')) {
                obj['isEqual'] = ApiClient.convertToType(data['isEqual'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
Matcher.prototype['name'] = undefined;

/**
 * @member {String} value
 */
Matcher.prototype['value'] = undefined;

/**
 * @member {Boolean} isRegex
 */
Matcher.prototype['isRegex'] = undefined;

/**
 * @member {Boolean} isEqual
 * @default true
 */
Matcher.prototype['isEqual'] = true;






export default Matcher;

