/**
 * Alertmanager API
 * API of the Prometheus Alertmanager (https://github.com/prometheus/alertmanager)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Alert from './Alert';
import PostableAlertAllOf from './PostableAlertAllOf';

/**
 * The PostableAlert model module.
 * @module model/PostableAlert
 * @version 0.0.1
 */
class PostableAlert {
    /**
     * Constructs a new <code>PostableAlert</code>.
     * @alias module:model/PostableAlert
     * @implements module:model/PostableAlertAllOf
     * @implements module:model/Alert
     * @param labels {Object.<String, String>} 
     */
    constructor(labels) { 
        PostableAlertAllOf.initialize(this);Alert.initialize(this, labels);
        PostableAlert.initialize(this, labels);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, labels) { 
        obj['labels'] = labels;
    }

    /**
     * Constructs a <code>PostableAlert</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PostableAlert} obj Optional instance to populate.
     * @return {module:model/PostableAlert} The populated <code>PostableAlert</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostableAlert();
            PostableAlertAllOf.constructFromObject(data, obj);
            Alert.constructFromObject(data, obj);

            if (data.hasOwnProperty('startsAt')) {
                obj['startsAt'] = ApiClient.convertToType(data['startsAt'], 'Date');
            }
            if (data.hasOwnProperty('endsAt')) {
                obj['endsAt'] = ApiClient.convertToType(data['endsAt'], 'Date');
            }
            if (data.hasOwnProperty('annotations')) {
                obj['annotations'] = ApiClient.convertToType(data['annotations'], {'String': 'String'});
            }
            if (data.hasOwnProperty('labels')) {
                obj['labels'] = ApiClient.convertToType(data['labels'], {'String': 'String'});
            }
            if (data.hasOwnProperty('generatorURL')) {
                obj['generatorURL'] = ApiClient.convertToType(data['generatorURL'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Date} startsAt
 */
PostableAlert.prototype['startsAt'] = undefined;

/**
 * @member {Date} endsAt
 */
PostableAlert.prototype['endsAt'] = undefined;

/**
 * @member {Object.<String, String>} annotations
 */
PostableAlert.prototype['annotations'] = undefined;

/**
 * @member {Object.<String, String>} labels
 */
PostableAlert.prototype['labels'] = undefined;

/**
 * @member {String} generatorURL
 */
PostableAlert.prototype['generatorURL'] = undefined;


// Implement PostableAlertAllOf interface:
/**
 * @member {Date} startsAt
 */
PostableAlertAllOf.prototype['startsAt'] = undefined;
/**
 * @member {Date} endsAt
 */
PostableAlertAllOf.prototype['endsAt'] = undefined;
/**
 * @member {Object.<String, String>} annotations
 */
PostableAlertAllOf.prototype['annotations'] = undefined;
// Implement Alert interface:
/**
 * @member {Object.<String, String>} labels
 */
Alert.prototype['labels'] = undefined;
/**
 * @member {String} generatorURL
 */
Alert.prototype['generatorURL'] = undefined;




export default PostableAlert;

