/**
 * Alertmanager API
 * API of the Prometheus Alertmanager (https://github.com/prometheus/alertmanager)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Receiver model module.
 * @module model/Receiver
 * @version 0.0.1
 */
class Receiver {
    /**
     * Constructs a new <code>Receiver</code>.
     * @alias module:model/Receiver
     * @param name {String} 
     */
    constructor(name) { 
        
        Receiver.initialize(this, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name) { 
        obj['name'] = name;
    }

    /**
     * Constructs a <code>Receiver</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Receiver} obj Optional instance to populate.
     * @return {module:model/Receiver} The populated <code>Receiver</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Receiver();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
Receiver.prototype['name'] = undefined;






export default Receiver;

