/**
 * Alertmanager API
 * API of the Prometheus Alertmanager (https://github.com/prometheus/alertmanager)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Matcher from './Matcher';

/**
 * The Silence model module.
 * @module model/Silence
 * @version 0.0.1
 */
class Silence {
    /**
     * Constructs a new <code>Silence</code>.
     * @alias module:model/Silence
     * @param matchers {Array.<module:model/Matcher>} 
     * @param startsAt {Date} 
     * @param endsAt {Date} 
     * @param createdBy {String} 
     * @param comment {String} 
     */
    constructor(matchers, startsAt, endsAt, createdBy, comment) { 
        
        Silence.initialize(this, matchers, startsAt, endsAt, createdBy, comment);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, matchers, startsAt, endsAt, createdBy, comment) { 
        obj['matchers'] = matchers;
        obj['startsAt'] = startsAt;
        obj['endsAt'] = endsAt;
        obj['createdBy'] = createdBy;
        obj['comment'] = comment;
    }

    /**
     * Constructs a <code>Silence</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Silence} obj Optional instance to populate.
     * @return {module:model/Silence} The populated <code>Silence</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Silence();

            if (data.hasOwnProperty('matchers')) {
                obj['matchers'] = ApiClient.convertToType(data['matchers'], [Matcher]);
            }
            if (data.hasOwnProperty('startsAt')) {
                obj['startsAt'] = ApiClient.convertToType(data['startsAt'], 'Date');
            }
            if (data.hasOwnProperty('endsAt')) {
                obj['endsAt'] = ApiClient.convertToType(data['endsAt'], 'Date');
            }
            if (data.hasOwnProperty('createdBy')) {
                obj['createdBy'] = ApiClient.convertToType(data['createdBy'], 'String');
            }
            if (data.hasOwnProperty('comment')) {
                obj['comment'] = ApiClient.convertToType(data['comment'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/Matcher>} matchers
 */
Silence.prototype['matchers'] = undefined;

/**
 * @member {Date} startsAt
 */
Silence.prototype['startsAt'] = undefined;

/**
 * @member {Date} endsAt
 */
Silence.prototype['endsAt'] = undefined;

/**
 * @member {String} createdBy
 */
Silence.prototype['createdBy'] = undefined;

/**
 * @member {String} comment
 */
Silence.prototype['comment'] = undefined;






export default Silence;

