/**
 * Alertmanager API
 * API of the Prometheus Alertmanager (https://github.com/prometheus/alertmanager)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SilenceStatus model module.
 * @module model/SilenceStatus
 * @version 0.0.1
 */
class SilenceStatus {
    /**
     * Constructs a new <code>SilenceStatus</code>.
     * @alias module:model/SilenceStatus
     * @param state {module:model/SilenceStatus.StateEnum} 
     */
    constructor(state) { 
        
        SilenceStatus.initialize(this, state);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, state) { 
        obj['state'] = state;
    }

    /**
     * Constructs a <code>SilenceStatus</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SilenceStatus} obj Optional instance to populate.
     * @return {module:model/SilenceStatus} The populated <code>SilenceStatus</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SilenceStatus();

            if (data.hasOwnProperty('state')) {
                obj['state'] = ApiClient.convertToType(data['state'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/SilenceStatus.StateEnum} state
 */
SilenceStatus.prototype['state'] = undefined;





/**
 * Allowed values for the <code>state</code> property.
 * @enum {String}
 * @readonly
 */
SilenceStatus['StateEnum'] = {

    /**
     * value: "expired"
     * @const
     */
    "expired": "expired",

    /**
     * value: "active"
     * @const
     */
    "active": "active",

    /**
     * value: "pending"
     * @const
     */
    "pending": "pending"
};



export default SilenceStatus;

