/**
 * Alertmanager API
 * API of the Prometheus Alertmanager (https://github.com/prometheus/alertmanager)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The VersionInfo model module.
 * @module model/VersionInfo
 * @version 0.0.1
 */
class VersionInfo {
    /**
     * Constructs a new <code>VersionInfo</code>.
     * @alias module:model/VersionInfo
     * @param version {String} 
     * @param revision {String} 
     * @param branch {String} 
     * @param buildUser {String} 
     * @param buildDate {String} 
     * @param goVersion {String} 
     */
    constructor(version, revision, branch, buildUser, buildDate, goVersion) { 
        
        VersionInfo.initialize(this, version, revision, branch, buildUser, buildDate, goVersion);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, version, revision, branch, buildUser, buildDate, goVersion) { 
        obj['version'] = version;
        obj['revision'] = revision;
        obj['branch'] = branch;
        obj['buildUser'] = buildUser;
        obj['buildDate'] = buildDate;
        obj['goVersion'] = goVersion;
    }

    /**
     * Constructs a <code>VersionInfo</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/VersionInfo} obj Optional instance to populate.
     * @return {module:model/VersionInfo} The populated <code>VersionInfo</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VersionInfo();

            if (data.hasOwnProperty('version')) {
                obj['version'] = ApiClient.convertToType(data['version'], 'String');
            }
            if (data.hasOwnProperty('revision')) {
                obj['revision'] = ApiClient.convertToType(data['revision'], 'String');
            }
            if (data.hasOwnProperty('branch')) {
                obj['branch'] = ApiClient.convertToType(data['branch'], 'String');
            }
            if (data.hasOwnProperty('buildUser')) {
                obj['buildUser'] = ApiClient.convertToType(data['buildUser'], 'String');
            }
            if (data.hasOwnProperty('buildDate')) {
                obj['buildDate'] = ApiClient.convertToType(data['buildDate'], 'String');
            }
            if (data.hasOwnProperty('goVersion')) {
                obj['goVersion'] = ApiClient.convertToType(data['goVersion'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} version
 */
VersionInfo.prototype['version'] = undefined;

/**
 * @member {String} revision
 */
VersionInfo.prototype['revision'] = undefined;

/**
 * @member {String} branch
 */
VersionInfo.prototype['branch'] = undefined;

/**
 * @member {String} buildUser
 */
VersionInfo.prototype['buildUser'] = undefined;

/**
 * @member {String} buildDate
 */
VersionInfo.prototype['buildDate'] = undefined;

/**
 * @member {String} goVersion
 */
VersionInfo.prototype['goVersion'] = undefined;






export default VersionInfo;

