/**
 * Alertmanager API
 * API of the Prometheus Alertmanager (https://github.com/prometheus/alertmanager)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import AlertGroup from '../model/AlertGroup';

/**
* Alertgroup service.
* @module api/AlertgroupApi
* @version 0.0.1
*/
export default class AlertgroupApi {

    /**
    * Constructs a new AlertgroupApi. 
    * @alias module:api/AlertgroupApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getAlertGroups operation.
     * @callback module:api/AlertgroupApi~getAlertGroupsCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/AlertGroup>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get a list of alert groups
     * @param {Object} opts Optional parameters
     * @param {Boolean} opts.active Show active alerts (default to true)
     * @param {Boolean} opts.silenced Show silenced alerts (default to true)
     * @param {Boolean} opts.inhibited Show inhibited alerts (default to true)
     * @param {Array.<String>} opts.filter A list of matchers to filter alerts by
     * @param {String} opts.receiver A regex matching receivers to filter alerts by
     * @param {module:api/AlertgroupApi~getAlertGroupsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/AlertGroup>}
     */
    getAlertGroups(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'active': opts['active'],
        'silenced': opts['silenced'],
        'inhibited': opts['inhibited'],
        'filter': this.apiClient.buildCollectionParam(opts['filter'], 'multi'),
        'receiver': opts['receiver']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [AlertGroup];
      return this.apiClient.callApi(
        '/alerts/groups', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
