/**
 * Alertmanager API
 * API of the Prometheus Alertmanager (https://github.com/prometheus/alertmanager)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import Receiver from '../model/Receiver';

/**
* Receiver service.
* @module api/ReceiverApi
* @version 0.0.1
*/
export default class ReceiverApi {

    /**
    * Constructs a new ReceiverApi. 
    * @alias module:api/ReceiverApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getReceivers operation.
     * @callback module:api/ReceiverApi~getReceiversCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Receiver>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get list of all receivers (name of notification integrations)
     * @param {module:api/ReceiverApi~getReceiversCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/Receiver>}
     */
    getReceivers(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [Receiver];
      return this.apiClient.callApi(
        '/receivers', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
