/**
 * Alertmanager API
 * API of the Prometheus Alertmanager (https://github.com/prometheus/alertmanager)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AlertmanagerApi);
  }
}(this, function(expect, AlertmanagerApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AlertmanagerApi.AlertmanagerStatus();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AlertmanagerStatus', function() {
    it('should create an instance of AlertmanagerStatus', function() {
      // uncomment below and update the code to test AlertmanagerStatus
      //var instane = new AlertmanagerApi.AlertmanagerStatus();
      //expect(instance).to.be.a(AlertmanagerApi.AlertmanagerStatus);
    });

    it('should have the property cluster (base name: "cluster")', function() {
      // uncomment below and update the code to test the property cluster
      //var instance = new AlertmanagerApi.AlertmanagerStatus();
      //expect(instance).to.be();
    });

    it('should have the property versionInfo (base name: "versionInfo")', function() {
      // uncomment below and update the code to test the property versionInfo
      //var instance = new AlertmanagerApi.AlertmanagerStatus();
      //expect(instance).to.be();
    });

    it('should have the property config (base name: "config")', function() {
      // uncomment below and update the code to test the property config
      //var instance = new AlertmanagerApi.AlertmanagerStatus();
      //expect(instance).to.be();
    });

    it('should have the property uptime (base name: "uptime")', function() {
      // uncomment below and update the code to test the property uptime
      //var instance = new AlertmanagerApi.AlertmanagerStatus();
      //expect(instance).to.be();
    });

  });

}));
