/**
 * Alertmanager API
 * API of the Prometheus Alertmanager (https://github.com/prometheus/alertmanager)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AlertmanagerApi);
  }
}(this, function(expect, AlertmanagerApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AlertmanagerApi.VersionInfo();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('VersionInfo', function() {
    it('should create an instance of VersionInfo', function() {
      // uncomment below and update the code to test VersionInfo
      //var instane = new AlertmanagerApi.VersionInfo();
      //expect(instance).to.be.a(AlertmanagerApi.VersionInfo);
    });

    it('should have the property version (base name: "version")', function() {
      // uncomment below and update the code to test the property version
      //var instance = new AlertmanagerApi.VersionInfo();
      //expect(instance).to.be();
    });

    it('should have the property revision (base name: "revision")', function() {
      // uncomment below and update the code to test the property revision
      //var instance = new AlertmanagerApi.VersionInfo();
      //expect(instance).to.be();
    });

    it('should have the property branch (base name: "branch")', function() {
      // uncomment below and update the code to test the property branch
      //var instance = new AlertmanagerApi.VersionInfo();
      //expect(instance).to.be();
    });

    it('should have the property buildUser (base name: "buildUser")', function() {
      // uncomment below and update the code to test the property buildUser
      //var instance = new AlertmanagerApi.VersionInfo();
      //expect(instance).to.be();
    });

    it('should have the property buildDate (base name: "buildDate")', function() {
      // uncomment below and update the code to test the property buildDate
      //var instance = new AlertmanagerApi.VersionInfo();
      //expect(instance).to.be();
    });

    it('should have the property goVersion (base name: "goVersion")', function() {
      // uncomment below and update the code to test the property goVersion
      //var instance = new AlertmanagerApi.VersionInfo();
      //expect(instance).to.be();
    });

  });

}));
